/* Mock market API for the Market Overview prototype.
   Stands in for the real service: the page sends its filters and gets back
   everything the five story chapters need, after a short network-like delay.
   Data comes from mock/market-data.js (window.MOCK_MARKET), generated by
   mock/generate.mjs. All figures are illustrative.

   MarketAPI.overview({company, peers, archetypes, functions, locations, period, industries})
     → Promise<snapshot>

   Two clocks: job posts run to the refresh month; hires come from profiles,
   which people update weeks after they move, so hire windows end one month
   earlier. Every comparison is with the same months a year before. */
(function(){
  const D = window.MOCK_MARKET;
  const LAST = D.months.length - 1;          // Aug 2026, job posts
  const HLAST = LAST - 1;                    // Jul 2026, hires
  const LEN = {'Last 30 days':1, 'Last 90 days':3, 'Last 6 months':6};
  const NEXT = {'Last 30 days':'30 Sep 2026', 'Last 90 days':'30 Nov 2026', 'Last 6 months':'28 Feb 2027'};
  // skill clusters, per department: each department's heatmap uses its own
  const CLUSTERS = {
    'Engineering': [['AI & ML',['LLM / RAG','CUDA']], ['Cloud & platform',['Kubernetes','Terraform','AWS']], ['Backend systems',['Java','Go','Kafka']], ['Frontend',['React','TypeScript']], ['Embedded & security',['RTOS','Rust']]],
    'Data & AI':   [['GenAI & LLMs',['LLM / RAG']], ['Deep learning',['CUDA']], ['Data engineering',['Spark','Kafka']], ['Analytics',['SQL']], ['MLOps',['Kubernetes','AWS']]],
    'Product':     [['AI product',['AI product strategy','LLM / RAG']], ['Platform & APIs',['API design']], ['Growth & data',['Experimentation','SQL']], ['Discovery',['User research']], ['Delivery',['Agile delivery']]],
    'Design':      [['AI interaction',['AI interaction design']], ['Design systems',['Design systems']], ['Research',['User research','Experimentation']], ['Prototyping',['Figma prototyping']]],
    'Sales':       [['AI selling',['AI solution selling']], ['Enterprise deals',['Enterprise negotiation']], ['Technical sales',['Solution demos']], ['Pipeline & CRM',['Salesforce CRM']], ['Partnerships',['Partner management']]],
    'Finance':     [['Modelling & FP&A',['Financial modelling']], ['SaaS metrics',['SaaS metrics']], ['Automation',['Finance automation']], ['Compliance & tax',['Ind AS / IFRS']], ['Analytics',['SQL']]],
    'Operations':  [['AI operations',['Agent operations']], ['Process automation',['RPA / automation']], ['Programme delivery',['Program management','Agile delivery']], ['Vendors',['Vendor management']], ['Analytics',['SQL']]],
    'People':      [['Talent acquisition',['Technical sourcing']], ['People analytics',['People analytics']], ['HR tech',['HRIS / Workday']], ['Rewards',['Compensation design']], ['Learning & AI skills',['AI upskilling','Program management']]],
  };

  const FN_TREND = {Engineering:0, 'Data & AI':9, Product:-4, Design:-7, Sales:-11, Finance:-5, Operations:-9, People:-13};
  const CITY_TREND = {Bengaluru:0, Hyderabad:5, Pune:3, NCR:-2, Chennai:-3, Mumbai:-4, Coimbatore:7, Ahmedabad:4, Kochi:1, Remote:2};
  const sum = (a, end, len) => { let t = 0; for (let m = end - len + 1; m <= end; m++) t += a[m] || 0; return t; };
  const yoy = (cur, prev) => prev ? Math.round((cur / prev - 1) * 100) : 0;
  const share = (mixObj, keys) => keys.length ? keys.reduce((a, k) => a + (mixObj[k] || 0), 0) : 1;
  const label = (end, len) => len === 1 ? D.months[end] : `${D.months[end - len + 1].split(' ')[0]} – ${D.months[end]}`;
  const median = v => { const s = [...v].sort((a, b) => a - b); return s.length ? s[Math.floor(s.length / 2)] : 0; };

  function overview(f){
    const L = LEN[f.period] || 1;
    const fns = f.functions || [], locs = f.locations || [], inds = f.industries || [];
    const peers = new Set(f.peers || []), arch = new Set(f.archetypes || []);

    /* ── companies: your people moving to and from them ── */
    const inInd = c => !inds.length || inds.includes(c.ind);
    const k = c => share(c.fn, fns) * share(c.city, locs);
    const inCohort = c => peers.has(c.n) || arch.has(c.arch);
    const all = D.companies.filter(inInd).map(c => {
      const kk = k(c);
      const out = Math.round(sum(c.out, HLAST, L) * kk), inn = Math.round(sum(c.in, HLAST, L) * kk);
      const outPrev = Math.round(sum(c.out, HLAST - L, L) * kk);
      const he = sum(c.hePosts, LAST, L), heLY = sum(c.hePosts, LAST - 12, L);
      // behaviour describes the company as a whole, over at least a quarter, not your filtered slice
      const LB = Math.max(L, 3), sen = sum(c.senHires, HLAST, LB);
      return { n:c.n, type:c.type, arch:c.arch, ind:c.ind, team:c.team, peer:peers.has(c.n), cohort:inCohort(c),
        out, in:inn, net:inn - out, outPrev, ramp:yoy(he, heLY),
        hi: sen / c.size, de: sum(c.hePosts, LAST, LB) / (sum(c.posts, LAST, LB) || 1), sen,
        entrant: c.first >= 12 && c.first <= LAST, first:c.first, what:c.what, press:c.press, levelUp:c.levelUp, tenure:c.tenure };
    });
    const cohort = all.filter(c => c.cohort);
    const scored = cohort.filter(c => c.sen >= 3);
    const mHi = median(scored.map(c => c.hi)), mDe = median(scored.map(c => c.de));
    all.forEach(c => {
      c.beh = c.sen < 3 ? 'Too little data'
        : c.hi > mHi && c.de > mDe ? 'Aggressive builder'
        : c.de > mDe ? 'Emerging builder'
        : c.hi > mHi ? 'Recently built' : 'Business as usual';
    });
    const moving = all.filter(c => c.out + c.in > 0).sort((a, b) => b.out - a.out);
    const out = moving.reduce((a, c) => a + c.out, 0), inn = moving.reduce((a, c) => a + c.in, 0);
    const wOut = (fn) => out ? moving.reduce((a, c) => a + fn(c) * c.out, 0) / out : 0;

    /* ── market: hiring across your cohort ── */
    const src = D.companies.filter(c => inInd(c) && inCohort(c));
    // departments and cities do not all move together: this year's hiring is tilted by the mix in scope
    const allF = fns.length ? fns : D.funcs, allL = locs.length ? locs : D.cities.map(x => x.n);
    const tilt = c => {
      const fw = allF.reduce((a, x) => a + (c.fn[x] || 0), 0) || 1, lw = allL.reduce((a, x) => a + (c.city[x] || 0), 0) || 1;
      return allF.reduce((a, x) => a + (c.fn[x] || 0) * (FN_TREND[x] || 0), 0) / fw + allL.reduce((a, x) => a + (c.city[x] || 0) * (CITY_TREND[x] || 0), 0) / lw;
    };
    const lean = (c, key, part) => 1 + tilt(c) * (key === 'senHires' ? .6 : 1) * part / 100;
    const mk = (key, end, part) => src.reduce((a, c) => a + sum(c[key], end, L) * k(c) * lean(c, key, part), 0);
    const hCur = mk('hires', HLAST, 1), hLY = mk('hires', HLAST - 12, 0), sCur = mk('senHires', HLAST, 1), sLY = mk('senHires', HLAST - 12, 0);
    const series = key => Array.from({length:12}, (_, i) => { const m = HLAST - 11 + i;
      const cur = src.reduce((a, c) => a + c[key][m] * k(c) * lean(c, key, (i + 1) / 12), 0), ly = src.reduce((a, c) => a + c[key][m - 12] * k(c), 0);
      return ly ? Math.round(cur / ly * 100) : 100; });

    /* ── roles in scope ── */
    const indK = inds.length ? Math.max(.05, inds.reduce((a, i) => a + (D.industries[i] || 0), 0) / Object.values(D.industries).reduce((a, b) => a + b, 0) * 1.6) : 1;
    const cityComp = locs.length ? D.cities.filter(c => locs.includes(c.n)).reduce((a, c) => a + c.comp, 0) / Math.max(1, locs.filter(l => D.cities.some(c => c.n === l)).length) : 1.2;
    const roles = D.roles.filter(r => !fns.length || fns.includes(r.f)).map(r => {
      const ck = share(r.city, locs), kk = ck * indK;
      const d = sum(r.demand, LAST, L) / L * kk, dLY = sum(r.demand, LAST - 12, L) / L * kk;
      const s = r.supply[LAST] * kk, sLY = r.supply[LAST - 12] * kk;
      const pay = sum(r.pay, LAST, L) / L, payLY = sum(r.pay, LAST - 12, L) / L;
      return { n:r.n, f:r.f, lvl:r.lvl, sk:r.sk, city:r.city, d:Math.round(d), s:Math.round(s), ratio: s ? d / s : 0, ratioLY: sLY ? dLY / sLY : 0,
        q: yoy(d, dLY), pay:+pay.toFixed(1), payYoY:+((pay / payLY - 1) * 100).toFixed(1) };
    }).filter(r => r.d > 0 && r.s > 0).sort((a, b) => b.d - a.d);

    const skillRatio = (n, ly) => { const s = D.skills[n]; return s ? s[0] / s[1] * (ly ? .9 : 1) * (1 + (cityComp - 1) * .3) : 0; };
    const cell = (r, sk, ly) => { const hit = r.sk.filter(x => sk.includes(x)); if (!hit.length) return null;
      return +((ly ? r.ratioLY : r.ratio) * .55 + hit.reduce((a, x) => a + skillRatio(x, ly), 0) / hit.length * .9).toFixed(2); };
    // one heatmap per department in scope, busiest department first
    const heatFor = f => {
      const cl = CLUSTERS[f], rs = roles.filter(r => r.f === f && r.sk.length).slice(0, 5);
      const colAvg = ly => cl.map(([, sk]) => { const v = rs.map(r => cell(r, sk, ly)).filter(x => x != null); return v.length ? v.reduce((a, b) => a + b, 0) / v.length : null; });
      const now = colAvg(false), before = colAvg(true);
      const ranked = cl.map((c, j) => ({ n:c[0], f, v:now[j], d: now[j] != null && before[j] != null ? now[j] - before[j] : 0 })).filter(c => c.v != null).sort((a, b) => b.v - a.v);
      return { f, clusters: cl.map(c => c[0]), rows: rs.map(r => ({ n:r.n, lvl:r.lvl, cells: cl.map(([, sk]) => cell(r, sk)) })),
        hard: ranked[0] || null, easy: ranked[ranked.length - 1] || null, ranked, jobs: roles.filter(r => r.f === f).reduce((a, r) => a + r.d, 0) };
    };
    const depts = (fns.length ? fns : D.funcs).filter(f => CLUSTERS[f]).map(heatFor).filter(h => h.rows.length).sort((a, b) => b.jobs - a.jobs);
    const ranked = depts.flatMap(h => h.ranked).sort((a, b) => b.v - a.v);
    const tech = depts.flatMap(h => roles.filter(r => r.f === h.f && r.sk.length).slice(0, 5));

    let pair = null;
    tech.forEach(r => { for (let i = 0; i < r.sk.length; i++) for (let j = i + 1; j < r.sk.length; j++) {
      const a = r.sk[i], b = r.sk[j], sa = D.skills[a], sb = D.skills[b]; if (!sa || !sb) continue;
      const sc = skillRatio(a) * skillRatio(b);
      if (!pair || sc > pair.sc) pair = { a, b, sc, both: Math.max(10, Math.round(Math.min(sa[1], sb[1]) * .12 * share(r.city, locs))) };
    }});

    const dayOf = (ratioKey) => { const w = roles.reduce((a, r) => a + r.d, 0) || 1; return Math.round(roles.reduce((a, r) => a + r.d * (26 + 9 * Math.min(4, r[ratioKey])), 0) / w); };

    /* ── cities for a hiring hub ── */
    const cityTight = c => { let d = 0, s = 0; roles.forEach(r => { const w = r.city[c.n] || 0; d += r.d * w; s += r.s * w; }); return s ? d / s : c.comp; };
    const hubs = D.cities.filter(c => c.n !== 'Bengaluru' && c.n !== 'Remote').map(c => {
      const people = Math.round(c.people[LAST] * share(c.fn, fns));
      const g = +((c.people[LAST] / c.people[Math.max(0, LAST - Math.max(L, 3))] - 1) * 100).toFixed(1);
      const comp = +(c.comp * .5 + cityTight(c) * .5).toFixed(2);
      return { n:c.n, people, growth:g, comp, payIdx:c.payIdx, yours: locs.includes(c.n),
        score: g * 3 + (2 - Math.min(2, comp)) * 12 + (100 - c.payIdx) * .3 + Math.log10(people + 1) * 20 };
    }).sort((a, b) => b.score - a.score);

    /* ── what's next ── */
    const themes = D.themes.filter(t => !fns.length || t.fns.some(x => fns.includes(x))).map(t => ({
      n:t.n, early:t.early, peers: Math.round(t.share[LAST] * cohort.length), pts: Math.round((t.share[LAST] - t.share[LAST - 12]) * 100) }));
    const titles = D.titles.filter(t => !fns.length || t[2].some(x => fns.includes(x))).map(t => ({ n:t[0], d:t[1], since:D.months[t[3]] }));

    /* ── since the last period ── */
    const since = [];
    const jump = [...moving].sort((a, b) => (b.out - b.outPrev) - (a.out - a.outPrev))[0];
    if (jump && jump.out > jump.outPrev) since.push({ k:'company', n:jump.n, t:`took ${jump.out - jump.outPrev} more of your people than the period before` });
    const harder = [...ranked].sort((a, b) => b.d - a.d)[0];
    if (harder && Math.abs(harder.d) > .02) since.push({ k:'cluster', n:harder.n, t: harder.d > 0 ? 'got harder to hire' : 'got easier to hire' });
    const ent = moving.filter(c => c.entrant).sort((a, b) => b.first - a.first)[0];
    if (ent) since.push({ k:'entrant', n:ent.n, t:'started hiring people like yours' });

    const sample = out + inn, seniorSample = Math.round(src.reduce((a, c) => a + sum(c.senHires, HLAST, L) * k(c), 0));
    return {
      meta: { company:f.company || D.you, period:f.period, refreshed:D.refreshed, next:NEXT[f.period] || NEXT['Last 30 days'],
        posts: label(LAST, L), hires: label(HLAST, L), postsLY: label(LAST - 12, L),
        sample, seniorSample, cohort: cohort.length, thin: sample < 250 || seniorSample < 40, empty: !moving.length || !roles.length },
      market: { allYoY: yoy(hCur, hLY), seniorYoY: yoy(sCur, sLY), share0: +(sLY / (hLY || 1) * 100).toFixed(1), share1: +(sCur / (hCur || 1) * 100).toFixed(1),
        series: { all: series('hires'), senior: series('senHires') } },
      you: { out, in:inn, net:inn - out, higherTitle: Math.round(wOut(c => c.levelUp) * 100), tenure: Math.round(wOut(c => c.tenure)) },
      companies: moving,
      movers: moving.filter(c => /Aggressive|Emerging/.test(c.beh) && c.ramp >= 10).sort((a, b) => b.ramp - a.ramp),
      entrants: moving.filter(c => c.entrant),
      feeders: moving.filter(c => c.in > c.out).sort((a, b) => b.net - a.net),
      oneWay: moving.filter(c => c.out >= 5 && c.in / c.out < .2),
      twoWay: moving.filter(c => c.out >= 5 && c.in / c.out >= .8),
      roles,
      heat: { depts, hard: ranked[0] || null, easy: ranked[ranked.length - 1] || null },
      pair,
      scale: roles.filter(r => r.ratio < 1).sort((a, b) => b.s - a.s).slice(0, 2),
      days: dayOf('ratio'), daysDelta: dayOf('ratio') - dayOf('ratioLY'),
      wage: [...roles].sort((a, b) => b.payYoY - a.payYoY).slice(0, 4).map(r => ({ n:r.n, v:r.payYoY })),
      hubs: hubs.slice(0, 3),
      rising: themes.filter(t => t.pts > 4).sort((a, b) => b.pts - a.pts).slice(0, 5),
      cooling: themes.filter(t => t.pts < -4).sort((a, b) => a.pts - b.pts).slice(0, 3),
      titles,
      since,
      totals: { roles: roles.reduce((a, r) => a + r.d, 0), people: roles.reduce((a, r) => a + r.s, 0) },
    };
  }

  window.MarketAPI = {
    overview(filters){
      const delay = 250 + Math.random() * 350;
      return new Promise((resolve, reject) => setTimeout(() => {
        if (window.MarketAPI.failNext) { window.MarketAPI.failNext = false; reject(new Error('Mock failure')); return; }
        try { resolve(overview(filters)); } catch (e) { reject(e); }
      }, delay));
    },
    overviewSync: overview,
    failNext: false,
  };
})();
